### ISSUE TITLE
When `localStorage` and/or `cookies` is disabled, contentstack breaks our JS bundle

### ISSUE THREAD

**Issue by benjaminhoffman** [contentstack/contentstack-javascript#11]
**Issue**: when cookie/localStorage is disabled, contentstack breaks the JS bundle.  Right now your library does _not_ appear to protect against situations where `localStorage` or `cookies` are blocked.  Unfortunately, this breaks _all_ the JS on our page

**Reproduce**: see screenshots below.  update your localStorage/cookie settings then load a browser that initializes contentstack on _runtime_.  

**solution**:  for starters, wrap this line in a try/catch block... I'm sure there is more you'll have to do but this is how I solve it whenever I'm writing to `localStorage`: https://github.com/contentstack/contentstack-javascript/blob/5280404b25a91c6ff585ef7e7840276f77fe53ca/src/core/cache.js#L15

## Browser error:
![error](https://user-images.githubusercontent.com/6520022/53047439-449d6980-3447-11e9-9461-7b0686f07d2f.png)

# How to update settings in browsers...

## Safari
![safari](https://user-images.githubusercontent.com/6520022/53047441-449d6980-3447-11e9-969f-3fbe45e194a8.png)

## Chrome
![chrome](https://user-images.githubusercontent.com/6520022/53047442-45360000-3447-11e9-8ba8-19c4da758a66.png)

## Firefox
![firefox](https://user-images.githubusercontent.com/6520022/53047443-45360000-3447-11e9-8573-84d50c8fe91c.png)

**Comment by hiteshbal91** [comment]
Hello @benjaminhoffman 

Looks like a critical issue, thank you for bringing this up to the engineering team. We are looking into it and get back to you asap.

**Comment by benjaminhoffman** [comment]
thx @rohitmishra209.  i tried to follow the commits / diffs but there was a bunch.  mind linking to the lines of code that addressed this issue?  thank you!
