### ISSUE TITLE
Reporting Typo on JavaScript Content Delivery SDK Docs

### ISSUE THREAD

**Issue by ajeetchaulagain** [contentstack/contentstack-javascript#149]
While looking at the docs of Javascript Content Delivery SDK, noticed there is a minor typo. Didn't find any repo where the docs are managed, therefore reporting here

- should be **referenceIn with raw queries:** instead of **referenceNotIn with raw queries:** in a title

https://www.contentstack.com/docs/developers/sdks/content-delivery-sdk/javascript-browser/reference#query-referencein

**Comment by nadeem-cs** [comment]
Thanks @ajeetchaulagain for raising this. This has been addressed and the changes will be live shortly.
