### ISSUE TITLE
[Feature Request] Type Definition Files

### ISSUE THREAD

**Issue by hjfitz** [contentstack/contentstack-javascript#20]
As a TypeScript developer, I'd love if there were type definition files to use throughout my projects!

**Comment by domness** [comment]
I've started working on https://www.npmjs.com/package/@types/contentstack which may help out until they're done officially.

**Comment by domness** [comment]
With the new releases, the DefinitelyTyped version is now behind and so will need updating to support any new features in this library until types are added at source.

**Comment by sdailly** [comment]
> @domness nous y travaillons pour créer des définitions TypeScript.

Do you have a release date?

**Comment by uttamukkoji** [comment]
Hey @sdailly, at this moment we can not give a date but we have added this feature request in our backlog. We are planning to release type definition files by mid-September.

**Comment by sdailly** [comment]
Any news about this feature ? :)

**Comment by uttamukkoji** [comment]
@sdailly  we are working on TS definitions and we’ll make it available in our next release which is planned in the last week of September 2020.

**Comment by uttamukkoji** [comment]
@hjfitz, @sdailly, @domness 

We’ve released a new version v3.11.0 and it includes TypeScript definitions. Hope you find this release helpful. We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by hjfitz** [comment]
Thank you @uttamukkoji, awesome stuff!
