### ISSUE TITLE
Double encoding of query params

### ISSUE THREAD

**Issue by PSoltes** [contentstack/contentstack-javascript#201]
In this file https://github.com/contentstack/contentstack-javascript/blob/8b33df9d033e8fd10ce5d9d52cef54bc3f1bb515/src/core/lib/request.js#L112

introduced by this commit(s)
- https://github.com/contentstack/contentstack-javascript/commit/c65d211c396d42f739aa3e499ce3b77e9f940de2
- https://github.com/contentstack/contentstack-javascript/commit/c65d211c396d42f739aa3e499ce3b77e9f940de2

Longer explanation
- `query` query param is already encoded on line 26 ` k + "=" + encodeURIComponent(p !== 'query' ? v : JSON.stringify(v)));`
- you can see this by enabling debug logs or console loging request.url
- whole url is reencoded again on line 112 ` fetch(encodeURI(request.url), request.option)`

**Comment by sunil-lakshman** [comment]
@PSoltes Thank you for bringing the issue to our attention. We have resolved it and released an updated version of the package. 
Please check the latest release below.
Link: https://www.npmjs.com/package/contentstack/v/3.20.3

CC: @harshithad0703 @netrajpatel
