### ISSUE TITLE
Sync functions returns an empty array

### ISSUE THREAD

**Issue by ematseruk** [contentstack/contentstack-javascript#46]
Hi,

I try to use the `sync` function of the client as per documentation:

```
Stack.sync({
                    init: true,
                })
                .then(((syncResult) => {
                    console.log(syncResult); // displays: []
                    resolve();
                }) as any)
                .catch((e) => {
                    console.log(e);
                    reject(e);
                });
```
It returns an empty array in the response on every call.

**Comment by uttamukkoji** [comment]
Hi @ematseruk,

Thanks for raising issue. Can you please check if you have publish contents (Entries and Assets) on environment you are passing while initialising Stack?

**Comment by ematseruk** [comment]
@uttamukkoji ,

Yes, I have the content published to target env. Environemnt name is passed to the config when Stack client is initialized: `this.client = new ContentStack.Stack(config);`

Config object is:
```
{
 api_key: env.contentStack.apiKey,
 delivery_token: env.contentStack.deliveryToken,
 environment: env.contentStack.environment,
}
```

All other simple requests to the same Stack work correctly.

**Comment by uttamukkoji** [comment]
@ematseruk can we connect from Contentstack support so we can get more details on this?

**Comment by ematseruk** [comment]
I don't think that the problem is connected with ContentStack's Delivery API. I have checked that it works fine here: https://www.contentstack.com/docs/developers/apis/content-delivery-api/?locale=europe#initial-sync and also using postman.

Via postman I was able to send the request and got a valid response:
![image](https://user-images.githubusercontent.com/36712576/113264855-1eac4980-92dc-11eb-9423-2dbed3058266.png)

**Comment by uttamukkoji** [comment]
Hey @ematseruk, 

Can we connect from the Contentstack support? So we can get more details and figure out the issue that you are facing.

**Comment by ematseruk** [comment]
hi @uttamukkoji,

I did the further investigation of the code and found that the sync data is not processed correctly in case cache policy is set to a value which is different  from `IGNORE_CACHE`. More details can be found on this [line](https://github.com/contentstack/contentstack-javascript/blob/master/src/core/lib/utils.js#L307). The `callback` method returns entries object for most cache policies (except `IGNORE_CACHE`)

Also, with the reference to the code, when the `sync` function is used, the cache is completely ignored (received data is never set in storage). 

Regarding the possible resolution for the issue. Maybe it forth at least to mention that `sync` method works correctly only in cases `IGNORE_CACHE` cache policy is used.

Regarding the ContentStack support. Do they responsible for the troubleshooting of issues related to clients for the Delivery API? I was thinking that they process only issues related to the API itself.

**Comment by uttamukkoji** [comment]
Hey @ematseruk,

Thanks for the details, we will update the documentation for the `sync` function as sync will not support cache policy.

Our Contentstack Support response on all the query even regarding the SDK or any other issue other than API. You can connect any time to our Contentstack Support team and they will be happy to resolve all your query. We also suggest SDK users to connect from Support so we can easily investigate and resolve any issue.

I am hoping you are getting expected response from sync function, if so, can we close this issue?

If you have any query or issue we can re-open or create new issue or we can connect through the Contentstack Support.

**Comment by ematseruk** [comment]
@uttamukkoji ,

Yep, if you don't need the issue to track activities realted to the documentation update, than I don't mind if the issue is closed.

**Comment by uttamukkoji** [comment]
Hi @ematseruk,

We have added note in the Readme, that Sync functionality is only supported when the cache policy is set to `IGNORE_CACHE`. You can find note in [Initial Sync](https://github.com/contentstack/contentstack-javascript/blob/master/README.md#initial-sync).

I am closing this issue, if you have any query or issue we can re-open or create new issue.
