### ISSUE TITLE
IE11 Support

### ISSUE THREAD

**Issue by mbeck-sans** [contentstack/contentstack-javascript#49]
Does the IE11 support mentioned at [What You Need to Get Started](https://www.contentstack.com/docs/developers/contentstack-basics/what-you-need-to-get-started/) apply to this repo?

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contentstack IE11</title>
</head>
<body>
    <p>hi there!</p>
    <script src="https://assets.contentstack.io/v3/assets/blt23180bf2502c7444/blt7c37c3a74961a31e/5f6db26872a0163a5b82a8d1/contentstack-v3.11.0.min.js"></script>
</body>
</html>
```

errors in IE11 with:

```
SCRIPT5007: Unable to set property 'Headers' of undefined or null reference
contentstack-v3.11.0.min.js (9,6715)
```

This error does not appear in v3.10.1.  Is [this change](https://github.com/contentstack/contentstack-javascript/compare/v3.10.1...v3.11.0#diff-01c3ef77cef4316fc02fa613aecf632a95cf6e38a26ee5fa066fc120b2fc60faR2) between v3.10.1 and v3.11.0 meant to be node-fetch for the client-side?

Changing to isomorphic-fetch/whatwg-fetch appears to make it pull in the correct client-side fetch polyfill.

**Comment by uttamukkoji** [comment]
Thanks @mbeck-sans for raising issue, We will check this on our side, and update you once we resolve issue.
