### ISSUE TITLE
@contentstack/utils brings a lot of dependencies that I would expect to be devDependencies

### ISSUE THREAD

**Issue by pveller** [contentstack/contentstack-javascript#52]
I am looking at two similar lambda functions - one with a deployment package of 500Kb and another of 12Mb. The difference is in how many `node_modules` each of them bring and specifically how many different `babel-*` modules one needs. I looked into it and all `babel-*` dependencies are coming from `contenstack -> @contenstack/utils`. So the difference between the two lambda functions is really in one using `contenstack` and one not. 

Would you please double check that you indeed need to bring the whole `babel` ecosystem into the fold with `@contentstack\utils`? 

This lambda used to run over contenstack HTTP API and in those days it weighted half of what it weighs now having migrated to the SDK.

**Comment by uttamukkoji** [comment]
Thanks for raising the issue @pveller, we will check this at our end and we will inform you our findings.

**Comment by uttamukkoji** [comment]
Hi @pveller,

We have updated the `@contentstack/utils` package dependency and move `babel-*` from the dependency to dev-dependency. New version `v3.13.2` for `contentstack` is published. 

Can you please check if you are still facing the issue?

**Comment by uttamukkoji** [comment]
Hi @pveller,

We are closing this issue for now. If you have any concern or issue you can re-open or create new issue on Contentstack JS repository.
