### ISSUE TITLE
Including references without specifying the reference uid

### ISSUE THREAD

**Issue by Fedeorlandau** [contentstack/contentstack-javascript#58]
Hi All,

We're building a nextjs app using Contentstack headless. 

We'd like to request if you could support including all the references to the entry. Most of our components include other components and since we're generating our pages on the server we can't predict the reference name

`.ContentType(type).Entry(uid).includeReferences()`

This is our current workflow:

- We look for the entries with the content type "page" then we build a page for each entry.
```
.ContentType('page')
    .Query()
    .includeCount()
    .includeContentType()
    .includeReference(['components'])
    .toJSON();
```

- We look for the "components" on each page and we map those components to react components.
```
.ContentType(type).Entry(uid).includeContentType()
    .toJSON();
```
- Some components include references to other components and this information is not available here, we only get the uid and the content type. 

JSON Example

```
{
  "components": [
    {
      "_version": 3,
      "locale": "en-us",
      "uid": "",
      "ACL": {
        
      },
      "_in_progress": false,
      "created_at": "2021-07-19T07:54:12.357Z",
      "created_by": "",
      "has_negative_margin": true,
      "listings": [
        {
          "uid": "asdasdasd",
          "_content_type_uid": "listing"
        }
      ],
      "tags": [
        
      ],
      "title": "Featured listings",
      "updated_at": "2021-07-19T08:20:34.134Z",
      "updated_by": "",
      "publish_details": {
        "environment": "",
        "locale": "en-us",
        "time": "2021-07-19T08:20:36.784Z",
        "user": ""
      },
      "_content_type_uid": "listing_grid"
    }
  ]
}
```

As you can see, the "listings" is an array of references and we need to include that information on the API call.

This is a dealbreaker in our app since we can't predict the references inside our components and we don't want to call the api on the client to do so.

Regards,

**Comment by Fedeorlandau** [comment]
A potential workaround would be renaming our props the following way:
instead of `listings` or `posts` or `countries` -> `ref_listings` `ref_posts` `ref_countries` and then with a regular expression loop on the `ref_*` props and query those entries. Finally replace `ref_listings` with the entries information.

But if you ever add a default prop starting with `ref_` it could break this workaround.

Regards,

**Comment by uttamukkoji** [comment]
Hi @Fedeorlandau,

Thanks for raising the issue. As I understand from the above details, you want to get child reference field details within the parent  reference. In above example you have parent reference field `components` and in that you have child reference `listings` to be included in response. 

In this case, you need to use `components.listings` in the `includeReference` to include the `listings` reference. 

Following is example you can use to get expected response:

```js
.ContentType('page')
    .Query()
    .includeCount()
    .includeContentType()
    .includeReference(['components', 'components.listings'])
    .toJSON();
```

Here are docs for [API reference](https://www.contentstack.com/docs/developers/apis/content-delivery-api/#include-reference) and [JS SDK Documentation](https://www.contentstack.com/docs/developers/javascript-browser/api-reference/Entry.html#includeReference).

**Comment by Fedeorlandau** [comment]
Hi @uttamukkoji thanks for you reply.

Unfortunately, not all the `components` have the `listings` reference. A page component can be any kind of content type.

This is the error you get when you request an invalid reference: 
```
{
  error_message: 'Failed to fetch entries. Please try again with valid parameters.',
  error_code: 141,
  errors: { ref_listings_grid: [ 'is not a valid reference.' ] }
}
```

Imagine a "page" as an actually a web page and the components prop as a bucket for all the components the page has. It could contain a hero component, a carousel, a list of products. And each component could also contain more refs.

This is how I was able to implement my workaround

```
const query = getClient(true).ContentType(type).Entry(uid).includeContentType()
    .toJSON();
  const result = await query.fetch();

  const references: string[] = [];
  Object.entries(result).forEach((prop) => {
    if (prop[0].includes('ref_')) {
      references.push(prop[0]);
    }
  });

  const fullQuery = getClient(true).ContentType(type).Entry(uid).includeContentType()
    .includeReference(references)
    .toJSON();

  const fullResult = await fullQuery.fetch();
  return fullResult;
```

It does only work for 1 level of depth.

**Comment by Fedeorlandau** [comment]
So the request is:  allowing `includeReference('*')` to automatically populate all the refs + children ref information. We can't dynamically build all the pages if we need to specify the references name manually for each component on the page.

**Comment by Fedeorlandau** [comment]
I can see why you didn't implement it that way. An entry A could have a reference to another entry B that points to the original entry A creating an infinite loop.

**Comment by uttamukkoji** [comment]
Hi @Fedeorlandau ,

Currently allowing dynamic reference is not supported from our API as there may be conditions where entry are reference to each other that may cause dead lock. Hence, we allow user to pass reference field uid's in `includeReference` function and that will have control on development side to get only specific references.

**Comment by Fedeorlandau** [comment]
Got it! Thanks for answering. I'll raise this issue on the https://github.com/uniformdev/uniform-optimize-next-contentstack-starter repository. Regards

**Comment by uttamukkoji** [comment]
Closing this issue as API does not support `includeReferece` to automatically populate all reference.
