### ISSUE TITLE
Inconsistent naming in ContentTypeCollection interface

### ISSUE THREAD

**Issue by joeyGold1** [contentstack/contentstack-javascript#59]
When accessing the API, a `ContentTypeCollection `object is returned. This has type
`{content_types:any[]}`.

However, in the definition of the `ContentTypeCollection` interface in `index.d.ts`, it specifies that `ContentTypeCollection `has field `contentTypes` instead of `content_types`.

**Comment by uttamukkoji** [comment]
Hi @joeyGold1 ,

We have resolved the issue related to `ContentTypeCollection` with field `content_types`. 
We are closing this issue for now. If you have any concern or issue you can re-open or create new issue on Contentstack JS repository.
