### ISSUE TITLE
Content Security Policy blocks the use of eval

### ISSUE THREAD

**Issue by dan2kx** [contentstack/contentstack-javascript#65]
We have a CSP that blocks the use of unsafe-eval and that is giving a warning:

```
The Content Security Policy (CSP) prevents the evaluation of arbitrary strings as JavaScript to make it more difficult for an attacker to inject unathorized code on your site.

To solve this issue, avoid using eval(), new Function(), setTimeout([string], ...) and setInterval([string], ...) for evaluating strings.

If you absolutely must: you can enable string evaluation by adding unsafe-eval as an allowed source in a script-src directive.
⚠️ Allowing string evaluation comes at the risk of inline script injection.
```

**Comment by uttamukkoji** [comment]
Hi @dan2kx ,

Thanks for raising issue, we are looking into this. It will be helpful if you can provide more details or sample app where you are facing this issue. This will help us to identify the cause of this issue and resolve it ASAP.

**Comment by dan2kx** [comment]
I think the problem is the dist/web/contentstacj.js file, if  you so a search there is a call to `new Function("return this")()` which seems to be where its getting caught by the policy

**Comment by uttamukkoji** [comment]
Thanks @dan2kx, We will check this on our end and update you once we resolve this issue.

**Comment by harshithad0703** [comment]
Hi @dan2kx 
we have removed the dist folder from the repo

cc: @sunil-lakshman
