### ISSUE TITLE
"include_dimension" in Query

### ISSUE THREAD

**Issue by idmedia-fritscher** [contentstack/contentstack-javascript#72]
Is there a way to include "include_dimension" in the query for an entry using the Contentstack js library? I tried fetchOptions but that doesn't seem to work.
Thanks!

**Comment by uttamukkoji** [comment]
Hi @idmedia-fritscher  

You can use 'addParam' method to add query parameters in request call. Here is API doc for your reference: https://www.contentstack.com/docs/developers/javascript-browser/api-reference/Entry.html#addParam

Let us know if you are able to get expected response using 'addParam'.
