### ISSUE TITLE
Huge bundle size

### ISSUE THREAD

**Issue by PSoltes** [contentstack/contentstack-javascript#84]
Hello, 
is there a way to only import stuff that it is used from this SDK? cause  i've tried importing all kinds of different way, but whole `contantstack` package is always imported. It is 253k so quite a bit of data, 10% of our whole bundle. So asking again is there a way to import less, or only specified parts?

**Comment by melvinhernandez** [comment]
@PSoltes were you able to dig into this further? I'm also running into the same issue.
