### ISSUE TITLE
Add a way to access whole fetch response on calls

### ISSUE THREAD

**Issue by PSoltes** [contentstack/contentstack-javascript#85]
Currently all response info except body is stripped during parsing process. Add a way to access this metadata about queries and requests for monitoring and tracing purposes.

**Comment by uttamukkoji** [comment]
Hey @PSoltes ,

Thanks for the raising issue, you can trace request, response and the error from the SDK by setting the `debug` to `true` as follow:

```js
const stack = Contentstack.Stack({ api_key: 'api_key', delivery_token: 'delivery_token', environment: 'environment', fetchOptions: {
   debug: true
}
});
```
This will enable logs from Contentstack JS SDK.

If you want to track logs you can use `logHandler` as follow:

```js
const stack = Contentstack.Stack({ api_key: 'api_key', delivery_token: 'delivery_token', environment: 'environment', fetchOptions: {
   debug: true,
   logHandler: (level, data) => {
      
   }
}
});
```
In this `level` is string value for log type and `data` will contain the details for the log.

**Comment by PSoltes** [comment]
Seems to be working as expected. Closing. Thanks again :muscle:
